-- MySQL Script generated by MySQL Workbench
-- Tue Feb 20 16:17:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Kategorijos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kategorijos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pavadinimas` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`Pasirinkimai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pasirinkimai` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pavadinimas` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`KategorijosPasirinkimai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`KategorijosPasirinkimai` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `kategorijosId` INT(11) NOT NULL,
  `pasirinkimoId` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `kategorijosId` (`kategorijosId` ASC),
  INDEX `pasirinkimoId` (`pasirinkimoId` ASC),
  CONSTRAINT `kategorijospasirinkimai_ibfk_1`
    FOREIGN KEY (`kategorijosId`)
    REFERENCES `mydb`.`Kategorijos` (`id`),
  CONSTRAINT `kategorijospasirinkimai_ibfk_2`
    FOREIGN KEY (`pasirinkimoId`)
    REFERENCES `mydb`.`Pasirinkimai` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`Produktai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produktai` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pavadinimas` VARCHAR(255) NULL DEFAULT NULL,
  `aprasymas` TEXT NULL DEFAULT NULL,
  `paveiksliukas` VARCHAR(255) NULL DEFAULT NULL,
  `gamintojas` VARCHAR(255) NULL DEFAULT NULL,
  `produkto_puslapis` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`ProduktoKategorijosIrPasirinkimai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProduktoKategorijosIrPasirinkimai` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `produktoId` INT(11) NOT NULL,
  `kategorijosId` INT(11) NOT NULL,
  `pasirinkimoId` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `produktoId` (`produktoId` ASC),
  INDEX `kategorijosId` (`kategorijosId` ASC),
  INDEX `pasirinkimoId` (`pasirinkimoId` ASC),
  CONSTRAINT `produktokategorijosirpasirinkimai_ibfk_1`
    FOREIGN KEY (`produktoId`)
    REFERENCES `mydb`.`Produktai` (`id`),
  CONSTRAINT `produktokategorijosirpasirinkimai_ibfk_2`
    FOREIGN KEY (`kategorijosId`)
    REFERENCES `mydb`.`Kategorijos` (`id`),
  CONSTRAINT `produktokategorijosirpasirinkimai_ibfk_3`
    FOREIGN KEY (`pasirinkimoId`)
    REFERENCES `mydb`.`Pasirinkimai` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
