-- MySQL Script generated by MySQL Workbench
-- Thu Mar  7 08:56:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tomasbudrikas10$mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tomasbudrikas10$mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tomasbudrikas10$mydb` DEFAULT CHARACTER SET utf8 ;
USE `tomasbudrikas10$mydb` ;

-- -----------------------------------------------------
-- Table `tomasbudrikas10$mydb`.`kategorijos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tomasbudrikas10$mydb`.`kategorijos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pavadinimas` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tomasbudrikas10$mydb`.`pasirinkimai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tomasbudrikas10$mydb`.`pasirinkimai` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pavadinimas` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tomasbudrikas10$mydb`.`kategorijospasirinkimai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tomasbudrikas10$mydb`.`kategorijospasirinkimai` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `kategorijosId` INT(11) NOT NULL,
  `pasirinkimoId` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `kategorijosId` (`kategorijosId` ASC),
  INDEX `pasirinkimoId` (`pasirinkimoId` ASC),
  CONSTRAINT `kategorijospasirinkimai_ibfk_1`
    FOREIGN KEY (`kategorijosId`)
    REFERENCES `tomasbudrikas10$mydb`.`kategorijos` (`id`),
  CONSTRAINT `kategorijospasirinkimai_ibfk_2`
    FOREIGN KEY (`pasirinkimoId`)
    REFERENCES `tomasbudrikas10$mydb`.`pasirinkimai` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tomasbudrikas10$mydb`.`produktai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tomasbudrikas10$mydb`.`produktai` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pavadinimas` VARCHAR(255) NULL DEFAULT NULL,
  `aprasymas` TEXT NULL DEFAULT NULL,
  `paveiksliukas` VARCHAR(255) NULL DEFAULT NULL,
  `gamintojas` VARCHAR(255) NULL DEFAULT NULL,
  `produkto_puslapis` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tomasbudrikas10$mydb`.`produktokategorijosirpasirinkimai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tomasbudrikas10$mydb`.`produktokategorijosirpasirinkimai` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `produktoId` INT(11) NOT NULL,
  `kategorijosId` INT(11) NOT NULL,
  `pasirinkimoId` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `produktoId` (`produktoId` ASC),
  INDEX `kategorijosId` (`kategorijosId` ASC),
  INDEX `pasirinkimoId` (`pasirinkimoId` ASC),
  CONSTRAINT `produktokategorijosirpasirinkimai_ibfk_1`
    FOREIGN KEY (`produktoId`)
    REFERENCES `tomasbudrikas10$mydb`.`produktai` (`id`),
  CONSTRAINT `produktokategorijosirpasirinkimai_ibfk_2`
    FOREIGN KEY (`kategorijosId`)
    REFERENCES `tomasbudrikas10$mydb`.`kategorijos` (`id`),
  CONSTRAINT `produktokategorijosirpasirinkimai_ibfk_3`
    FOREIGN KEY (`pasirinkimoId`)
    REFERENCES `tomasbudrikas10$mydb`.`pasirinkimai` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `tomasbudrikas10$mydb`.`vartotojai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tomasbudrikas10$mydb`.`vartotojai` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pavadinimas` VARCHAR(45) NOT NULL,
  `slaptazodis` VARCHAR(255) NOT NULL,
  `teises` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tomasbudrikas10$mydb`.`atsiliepimai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tomasbudrikas10$mydb`.`atsiliepimai` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `produktoId` INT(11) NOT NULL,
  `vartotojoId` INT(11) NOT NULL,
  `vertinimas` INT(2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_atsiliepimai_produktai1_idx` (`produktoId` ASC),
  INDEX `fk_atsiliepimai_vartotojai1_idx` (`vartotojoId` ASC),
  CONSTRAINT `fk_atsiliepimai_produktai1`
    FOREIGN KEY (`produktoId`)
    REFERENCES `tomasbudrikas10$mydb`.`produktai` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atsiliepimai_vartotojai1`
    FOREIGN KEY (`vartotojoId`)
    REFERENCES `tomasbudrikas10$mydb`.`vartotojai` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
